import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Home from '../components/Home'
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Basic Banking System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Home />        
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}
